language: java
jdk:
- oraclejdk8
- oraclejdk9
branches:
  only:
  - master
before_script:
- chmod +x gradlew
script:
- "./gradlew check jacocoRootReport"
after_success:
- "./gradlew sonarqube \
  -Dsonar.organization=itanoss-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=$SONAR_LOGIN"
env:
  sonarLogin:
    secure: hFOV1AI23thPnCc9p/EaH58fEhVrTtvR862ofE6cnQ817wAt5wmW6MdzMciaQDdPAzB1ES2AiSTc7kAz+wrl8U4SMR2k20Kd8knz0N0EeL5w0N7eZQa4em5sblYxOoXgC18ipXFenSOUrgV9iTIk1+AknJcjyS9Vvec6fyZOlx1z/Ya8W74qIhwbC3i146bFoJJN501037NJlxUrOIozt5RRGFfZxcpuQkkujtutp2/rx7KQz7gpZANinoV/1bOjVkSsSOI9cu/G/IgLln4MiEMYjbCXdqSJGUA8XNurH4lY+OGkr3lWNUQHfpXwBqc6njybXuCAhffjWNJXP3QJ/uZoRyyRc79VukmW/eywUCtdkqUcs1WyyUfbOhZ4F0NnkKpltTDvwyOz9rAsN68VyYs6Nb97Sg03UGji94Mr4wR+zwAIqy0ucgQctouDAAqA/VXipWaaeBRijq6hGFR9xMHmNZCLKd264mRxaoWXORDEiAB7CGJy+fay6czbtJQhAr9KZaqjSgEQFpiWnjPKFfuAqR/qfc5WtPsp4Pp8nKYLGjORvAH1bOQkwXeZDUt40e2PUajBwYRifQLfVA7xCB8A9p3d+XZaCOoG7pn2s62c/WWTtPw+UCK8Nkmp5gD53Safre9tX2iO+W3JRGo7jRa4rfYjfOVGNjmhXH0PPXQ=
